0x05. Python - Exceptions
Python

task 0

"""Prints x elements of a list, or all elements if x is greater than the length of the list.

  Args:
    my_list: A list of any type of elements.
    x: The number of elements to print.

  Returns:
    The real number of elements printed.
  """

task 1

"""Prints an integer with "{:d}".format().

  Args:
    value: Any type of value.

  Returns:
    True if the value is an integer and has been correctly printed, False otherwise.
  """

task 2
 """Prints the first x elements of a list and only integers.

  Args:
    my_list: A list of any type of elements.
    x: The number of elements to print.

  Returns:
    The real number of integers printed.

  Raises:
    IndexError: If x is greater than the length of my_list.
  """
  task 3
  """Divides 2 integers and prints the result.

  Args:
    a: An integer.
    b: An integer.

  Returns:
    The value of the division, or None if an error occurred.
  """
  task 4
  """Divides element by element 2 lists.

  Args:
    my_list_1: A list of any type of elements.
    my_list_2: A list of any type of elements.
    list_length: The length of the new list.

  Returns:
    A new list (length = list_length) with all divisions.
  """
  task 6 """Raises a name exception with a message.

  Args:
    message: The message of the exception.
  """
